ALTER TABLE budget_sources
    ADD COLUMN IF NOT EXISTS cut_transfer NUMERIC(15,3) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS under_budget NUMERIC(15,3) NOT NULL DEFAULT 0;

ALTER TABLE scenario_budget_sources
    ADD COLUMN IF NOT EXISTS cut_transfer NUMERIC(15,3) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS under_budget NUMERIC(15,3) NOT NULL DEFAULT 0;
